# ...existing code...
server:
  port: 9090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowed-headers: "*"
            allow-credentials: true

      routes:
        - id: productos-service
          uri: lb://productos-service
          predicates:
            - Path=/api/productos/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

        - id: categorias-service
          uri: lb://productos-service
          predicates:
            - Path=/api/categorias/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

        - id: identity-service-api
          uri: lb://identity-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: identity-service-oauth
          uri: lb://identity-service
          predicates:
            - Path=/oauth2/**
            - Path=/login/oauth2/code/**

        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/api/perfiles-usuario/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

        - id: ventas-service
          uri: lb://ventas-service
          predicates:
            - Path=/api/ventas/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

        - id: carrito-service
          uri: lb://ventas-service
          predicates:
            - Path=/api/carrito/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

        - id: notificaciones-ws
          uri: lb://notificaciones-service
          predicates:
            - Path=/api/notificaciones-ws/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
# ...existing code...