server:
  port: 9090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: productos-service
          uri: lb://productos-service
          predicates:
            - Path=/api/productos/**
          filters:
            - StripPrefix=1
            
        - id: categorias-service
          uri: lb://productos-service
          predicates:
            - Path=/api/categorias/**
          filters:
            - StripPrefix=1

        # --- ¡CORREGIDO! (Ruta 1 para API de Identity) ---
        - id: identity-service-api
          uri: lb://identity-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1 # Esto quita /api y lo manda como /auth/** al servicio
            
        # --- ¡NUEVO! (Ruta 2 para el flujo OAuth2) ---
        - id: identity-service-oauth
          uri: lb://identity-service
          predicates:
            - Path=/oauth2/**, /login/oauth2/code/**
          # Sin filtros, se pasa la ruta tal cual (ej: /oauth2/authorization/google)

        # --- ¡CORREGIDO! (El path ahora es /api/perfiles-usuario) ---
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/api/perfiles-usuario/** 
          filters:
            - StripPrefix=1 
            
        - id: ventas-service
          uri: lb://ventas-service
          predicates:
            - Path=/api/ventas/**
          filters:
            - StripPrefix=1
            - JwtAuthentication 
            
        - id: carrito-service
          uri: lb://ventas-service
          predicates:
            - Path=/api/carrito/**
          filters:
            - StripPrefix=1
            - JwtAuthentication 
            
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
jwt:
  secret: ${JWT_SECRET}
management:
  endpoints:
    web:
      exposure:
        include: "*"