server:
  port: 9090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*" 
            allowed-methods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowed-headers: "*"
            allow-credentials: true

      routes:
        - id: productos-service
          uri: lb://productos-service
          predicates:
            - Path=/api/productos/**
          filters:
            - StripPrefix=1
            - JwtAuthentication  # <--- ¡FILTRO AÑADIDO!
            
        - id: categorias-service
          uri: lb://productos-service
          predicates:
            - Path=/api/categorias/**
          filters:
            - StripPrefix=1
            - JwtAuthentication  # <--- ¡FILTRO AÑADIDO!

        # --- Ruta 1 para API de Identity (Pública) ---
        - id: identity-service-api
          uri: lb://identity-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
            
        # --- Ruta 2 para el flujo OAuth2 (Pública) ---
        - id: identity-service-oauth
          uri: lb://identity-service
          predicates:
            - Path=/oauth2/**, /login/oauth2/code/**

        # --- Ruta de Perfiles de Usuario (Segura) ---
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/api/perfiles-usuario/** 
          filters:
            - StripPrefix=1
            - JwtAuthentication  # <--- ¡FILTRO AÑADIDO!
            
        - id: ventas-service
          uri: lb://ventas-service
          predicates:
            - Path=/api/ventas/**
          filters:
            - StripPrefix=1
            - JwtAuthentication 
            
        - id: carrito-service
          uri: lb://ventas-service
          predicates:
            - Path=/api/carrito/**
          filters:
            - StripPrefix=1
            - JwtAuthentication 

        - id: notificaciones-ws
          uri: lb://notificaciones-service 
          predicates:
            - Path=/api/notificaciones-ws/**
          filters:
            - StripPrefix=1  
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
jwt:
  secret: ${JWT_SECRET}

# Configuración de Actuator para Prometheus
management:
  endpoints:
    web:
      exposure:
        include: "*" # Exponer todos los endpoints (incluye prometheus)
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
