server:
  port: 9090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:3000"
                  - "http://127.0.0.1:5500"
                  - "null" 
                  - "*" 
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
                allowCredentials: false

          routes:
            - id: productos-service
              uri: lb://productos-service
              predicates:
                - Path=/api/productos/**
              filters:
                - StripPrefix=1
                - JwtAuthentication

            - id: categorias-service
              uri: lb://productos-service
              predicates:
                - Path=/api/categorias/**
              filters:
                - StripPrefix=1
                - JwtAuthentication

            - id: identity-service-api
              uri: lb://identity-service
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=1

            - id: identity-service-oauth
              uri: lb://identity-service
              predicates:
                - Path=/oauth2/**, /login/oauth2/code/**

            - id: usuario-service
              uri: lb://usuario-service
              predicates:
                - Path=/api/perfiles-usuario/**
              filters:
                - StripPrefix=1
                - JwtAuthentication

            - id: ventas-service
              uri: lb://ventas-service
              predicates:
                - Path=/api/ventas/**
              filters:
                - StripPrefix=1
                - JwtAuthentication 

            - id: carrito-service
              uri: lb://ventas-service
              predicates:
                - Path=/api/carrito/**
              filters:
                - StripPrefix=1
                - JwtAuthentication 

            - id: notificaciones-ws-sockjs
              uri: lb://notificaciones-service
              predicates:
                - Path=/api/notificaciones-ws/**
              filters:
                - StripPrefix=1

            - id: notificaciones-ws-websocket
              uri: ws://notificaciones-service:9002
              predicates:
                - Path=/api/notificaciones-ws/**
                - Header=Upgrade, websocket
              filters:
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always