server:
  port: 9002

spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/notificacionesdb

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    fail-fast: false
    registry-fetch-interval-seconds: 5
    lease-renewal-interval-in-seconds: 5

  instance:
    hostname: notificaciones-service
    lease-expiration-duration-in-seconds: 10
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true