server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/usuariodb?createDatabaseIfNotExist=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          # Debe coincidir con la URL de tu identity-service (o un jwk-set-uri si lo configuras)
          # Por ahora, usaremos la clave secreta (simétrico)
          # Esta clave DEBE ser la misma que 'jwt.secret' en identity-service
          secret-key: ${JWT_SECRET}
  rabbitmq:
    host: rabbitmq     # El nombre del contenedor en docker-compose
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
