server:
  port: 8200 # Puerto del servicio de ventas

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/ventasdb?createDatabaseIfNotExist=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

productos:
  service:
    url: http://localhost:8080/api/productos

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
